Deprecate db function `get_workers`
taskcluster/taskcluster pull request #3620
Opened 2020-10-05 21:53 UTC by alopezz

Github Bug/Issue: Fixes #3538.

Work-in-progress.

Is this what is intended by the first point in the issue (the deprecation part)?

2020-10-06 14:29 UTC, djmitche requested changes
You'll also need to run `yarn generate` to update a few places that list functions and DB versions.

Also, this will cause worker-manager tests to fail, because worker-manager tests are now calling a deprecated method.  So those tests will need to be updated in the same PR.

2020-10-06 14:29 UTC, djmitche commented on db/versions/0052.yml
> +      begin
Close, but it needs a copy of the same body, as a deprecated method can still be called for two major Taskcluster releases.

2020-10-06 15:03 UTC, alopezz commented
> You'll also need to run `yarn generate` to update a few places that list functions and DB versions.

Thanks for the pointer! Note taken on having a copy of the body of the deprecated function as well.

> Also, this will cause worker-manager tests to fail, because worker-manager tests are now calling a deprecated method. So those tests will need to be updated in the same PR.

I thought as much! I was trying to get early feedback on the first part to make sure I had that right before trying to remove tests. I'm basing my understanding on the comments on PR #3520, but I still need to figure out some more things about the code. Is it preferable that I convert the PR to draft for now?

2020-10-06 15:39 UTC, djmitche commented
Draft sounds good, yeah.

2020-10-06 18:43 UTC, alopezz commented
I've changed the affected tests to use `get_workers_without_provider_data` instead of `get_workers`, and then using `get_worker_2` (via `Worker.get`) to get the necessary `providerData`.

Is there a better way? The only improvement I can think of is to move the statement that I repeated everywhere, such as
https://github.com/taskcluster/taskcluster/blob/03ef4111da3d6dd2de68b6e0ad2e9b2560349966/services/worker-manager/test/provider_aws_test.js#L125-L130
to `helper.js` at https://github.com/taskcluster/taskcluster/blob/03ef4111da3d6dd2de68b6e0ad2e9b2560349966/services/worker-manager/test/helper.js#L245-L247

Also I removed a couple of tests that referred to the deprecated function in db/test/fns/worker_manager_test.js. Is this the right thing to do here?

Finally, regarding the changelog, this is the way I guess I would have to do it, after reading the docs. Is it right?

```
yarn changelog --issue 3538 --minor --developers
```

2020-10-06 21:53 UTC, djmitche commented
That helper function sounds like a good idea.

And, `yarn changelog --issue 3538 --patch --developers` in this case, I think.

I'll have a deeper look tomorrow.  Thanks for working on this!

2020-10-07 10:56 UTC, alopezz commented
Regarding the level in the changelog, I thought it was minor because of [this](https://github.com/taskcluster/taskcluster/blob/main/dev-docs/best-practices/changelog.md#levels):

> minor: Any change that adds a new version to the database

Though in this case there are no schema changes so I'd see why this may not apply here.

2020-10-07 16:32 UTC, djmitche commented
> Regarding the level in the changelog, I thought it was minor because of [this](https://github.com/taskcluster/taskcluster/blob/main/dev-docs/best-practices/changelog.md#levels):
> 
> > minor: Any change that adds a new version to the database
> 
> Though in this case there are no schema changes so I'd see why this may not apply here.

Ah, good point.  Let's leave it at minor then.  You're right that this is a particularly minimal DB version that will have zero impact as measured on the db server, but it's best to be consistent in following best-practices!

Thanks for calling me out on that!

2020-10-07 16:33 UTC, djmitche reviewed
I'm happy to merge this once it has a changelog.

2020-10-07 17:15 UTC, djmitche approved these changes
Nice work -- thank you!  What's next?

2020-10-07 17:15 UTC, merged

2020-10-07 17:16 UTC, djmitche commented
@all-contributors please add @alopezz for code