Update release taskgraph to use on-resolved
taskcluster/taskcluster pull request #3889
Opened 2020-11-10 21:31 UTC by imbstack

Github Bug/Issue: Fixes #3684

2020-11-10 21:33 UTC, djmitche approved these changes

2020-11-10 21:55 UTC, djmitche requested changes
..except the decision task failed!

```
[task 2020-11-10T21:34:07.304Z] Exception: release-publish has invalid notification filter (on-resolved)
```

2020-11-11 21:25 UTC, imbstack commented
Looks like we'll need to patch taskgraph and release new taskgraph images first

2021-01-27 17:42 UTC, imbstack commented
I guess we need to pick this up again later

2021-01-27 17:42 UTC, closed without merging