Add listTaskQueues and getTaskQueue to queue service api
taskcluster/taskcluster pull request #3941
Opened 2020-11-17 19:37 UTC by alopezz

Github Bug/Issue: Fixes #3578 (part 2)

Follow-up to #3641 to add `listTaskQueues` and `getTaskQueue` methods to the queue service API, mapping to the future hierarchy of using taskQueueId in place of the pair provisionerId / workerType.

@djmitche Hopefully I understood this correctly :smiley:.

2020-11-17 19:47 UTC, imbstack requested changes
I haven't done an in-depth review, but this is looking good so far! I think just some quick updates to copy-pasted terms in documentation to begin with.

2020-11-17 19:47 UTC, imbstack commented on services/queue/schemas/v1/list-taskqueues-response.yml
> +            Date and time after which the worker-type will be automatically
I guess we'll need to update this to remove `workerType` etc?

2020-11-17 19:47 UTC, imbstack commented on services/queue/src/api.js
> +  title: 'Get a list of all active worker-types',
same here about changing the wording

2020-11-17 19:53 UTC, alopezz commented
@imbstack Right, it looks like I wasn't thorough enough with the replacements! I'll fix those in a moment; thank you for the feedback, I wanted to make sure that I was right on track.

2020-11-18 14:48 UTC, djmitche approved these changes
Looks good to me!  If you can push a `--patch` changelog and apply the below nit, I'll click "merge" :)

2020-11-18 14:48 UTC, djmitche commented on services/queue/schemas/v1/taskqueue-response.yml
> +      This is the stability of the worker-type. Accepted values:
```suggestion
      This is the stability of the task queue. Accepted values:
```

2020-11-18 16:03 UTC, alopezz commented on services/queue/schemas/v1/taskqueue-response.yml
> +      This is the stability of the worker-type. Accepted values:
:flushed:

2020-11-18 16:25 UTC, djmitche approved these changes

2020-11-18 16:46 UTC, djmitche commented
alles is groen!

2020-11-18 16:47 UTC, merged