use taskQueueId internally to the queue (functions and code for tasks)
taskcluster/taskcluster pull request #4122
Opened 2020-12-16 21:18 UTC by alopezz

Github Bug/Issue: Fixes #3578 

With #3987, the db will already store `task_queue_id`s rather than `provisioner_id` and `worker_type` for tasks. This PR implements the follow up of making the code also do this internally (while keeping external interfaces unchanged).

2020-12-21 21:48 UTC, djmitche requested changes
Aside from the below minor detail, this looks great!

2020-12-21 21:48 UTC, djmitche commented on db/versions/0061.yml
> +  create_task:
From what I can see, this is the same function from version 0060, but with `deprecated: true`.  As a shortcut, you can omit everything except `deprecated` for such changes.

2020-12-21 22:48 UTC, djmitche approved these changes
Looks good once it's green!  I pushed a `yarn generate`.

2020-12-22 15:06 UTC, merged

2020-12-22 16:47 UTC, alopezz commented
Yay! #3578 is finally really closed!