fix: web-server should check session when fetching
taskcluster/taskcluster pull request #4235
Opened 2021-01-10 14:19 UTC by rbrishabh

Fixes #3868 
 
 Hi @djmitche, sorry for the delay in getting back with this really short fix! 
 
 How does this look?
 I am afraid I will trouble you a little bit more!
 
 I've made the change but I'm not 100% sure how to check if it's working! Could you please help me with that?
 
 Thank you!

2021-01-11 19:33 UTC, djmitche approved these changes
Looks perfect!  I think this is sufficiently low-level that we can skip a changelog.

As for testing, I don't see an easy way to do so other than testing manually in a deployment, which I will do now.  I'll change the hash in the DB and in my browser, and see that the session s no longer valid.

2021-01-11 19:56 UTC, djmitche requested changes
Ah, it does look like `session_store_test.js` needs to be updated.

Within that file, you could test it as follows:

* Create a new session with `sessionid1`
* Use a DB query to update the `hashed_session_id` column to the hash `sessionid2`
* Try `session.get('sessionid2')`

I think that might involve calling `await helper.db._withDbClient(async client => { .. })` which is a little awkward since that `_` suggests you shouldn't be calling it -- but it's OK since this is in tests.

2021-01-16 11:43 UTC, rbrishabh commented
@djmitche thanks for your review!
how does this look now?
Thanks!

2021-01-17 00:34 UTC, djmitche commented
I'll take a look next week, but right off I notice that the test suite failed in CI -- perhaps you can take another look before then?

A changelog can be added with `yarn changelog --issue 3868 --silent`.

2021-01-19 18:14 UTC, djmitche requested changes

2021-01-19 18:14 UTC, djmitche commented on services/web-server/test/session_store_test.js
> +      await helper.db._withDbClient(async client => {
and here, I think you want `_withClient` :)

2021-01-19 18:14 UTC, djmitche commented on services/web-server/src/login/PostgresSessionStore.js
> +        } else if (db.decrypt({ value: row.data.encrypted_session_id }).toString('utf8') !== sessionId){
I think you want just `row.encrypted_session_id` here -- `data` is the session data itself.  That should fix the errors about `kid` in the tests.

2021-01-19 20:40 UTC, rbrishabh commented
thanks @djmitche! I'll get to those changes soon!
part of the reason why I couldn't notice those errors was because I'm yet to run taskcluster on my system! The changes I've made so far are just by looking at the schema!
It's in my plans to provision taskcluster and get back into full force very soon!
In the meantime, thanks for your patience and for your quick reviews!

2021-01-19 20:56 UTC, djmitche commented
Sure thing.  If you want a bit more sync help, you can check out #taskcluster at https://chat.mozilla.org/.

2021-01-19 21:54 UTC, djmitche commented
See #4280 for the better way to access `_withClient`.

2021-01-19 21:54 UTC, djmitche commented on services/web-server/test/session_store_test.js
> +      await helper.db._withDbClient(async client => {
(also, it needs a first argument of 'read' or, in this case 'write' -- that's another thing that #4280 makes easier)

2021-01-27 19:28 UTC, djmitche commented
@rbrishabh how is it going?

2021-01-27 20:04 UTC, rbrishabh commented
hi @djmitche! Had a busy week with work.
Getting to this during weekend!
Sorry for the delay!

2021-02-01 17:07 UTC, rbrishabh commented
Hi @djmitche!
Once again, I really apologize for the delay in making these tiny changes!!
I had a superbusy week!

Also, I think this looks good now!
What do you think?

2021-02-01 17:29 UTC, djmitche approved these changes
```
Error: Direct uses of DB found in services/: services/web-server/test/session_store_test.js:  helper.withDbClient = fn => helper.db._withClient('write', fn); (while executing task Services are not using node-pg)
```
wow, we even have a test for that -- I had forgotten!

I'll land my changes in #4279 right after this, and doing so should fix that failing test.

2021-02-01 17:36 UTC, merged