Role deletion from Roles Table
taskcluster/taskcluster pull request #4283
Opened 2021-01-20 21:07 UTC by mrsVelena

Github Bug/Issue: Fixes #2393

Added a delete action to each role in the list of roles

.

2021-01-21 19:30 UTC, djmitche requested changes
This looks like it's got the necessary pieces in place.  But, it has some linting failures that are preventing netlify from deploying it.  If you can get that fixed up, I can take another look.

The `service-auth` failure is because your work is based on an older branch (from a week or so ago).  It's fine to just leave that failing, as you haven't modified that service, but a rebase onto the latest commit on `main` will fix it.

2021-01-21 19:30 UTC, djmitche commented on ui/src/components/RolesTable/index.jsx
> +    onDialogActionOpen: func,
This prop is not checked for null-ness before being used, so it should have `.isRequired` like `onPageChange` does.  That also means you can omit it from `defaultProps`, below.

2021-01-25 16:50 UTC, petemoore commented
It looks like there may be some test failures in https://community-tc.services.mozilla.com/tasks/LHu8K21YQN6LmHKMD46ZQA/runs/0/logs/public/logs/live.log but I'm not too sure what is wrong...

2021-01-26 15:29 UTC, djmitche approved these changes
This is fantastic -- nice work!

One minor note that doesn't matter here, but will for the next PR: you should usually make a "topic branch" to work on a PR like this, so that your `main` branch can be updated to new versions of the shared `main` without losing your changes.  The [GitHub Flow](https://guides.github.com/introduction/flow/) doc has more information on that.  Once this is merged, you'll want to do something like

```
git checkout main
git fetch https://github.com/taskcluster/taskcluster main
git reset --hard FETCH_HEAD
```
and that will reset your `main` branch to the same commit as the taskcluster repo's `main` branch. Then you can create a topic branch for your next project:
```
git checkout -b my-next-project
# (or whatever you want to call the branch)
```

2021-01-26 15:29 UTC, merged