Added Delete button for individual Client records
taskcluster/taskcluster pull request #4322
Opened 2021-01-27 19:52 UTC by mrsVelena

Github Bug/Issue: Fixes #2393 for Clients page

2021-01-28 15:54 UTC, djmitche requested changes
One minor request: let's move the delete icon to the rightmost end of the list item, so instead of

![image](https://user-images.githubusercontent.com/28673/106163151-db582200-6156-11eb-9e9c-311040510e63.png)

it looks like

![image](https://user-images.githubusercontent.com/28673/106163474-32f68d80-6157-11eb-8ff5-5f2eeb4ae85b.png)

2021-01-28 15:54 UTC, djmitche commented on changelog/issue-2393.md
>  level: minor
I missed this on the earlier PR, but let's change this to "patch".  The guidelines for these levels are [here](https://github.com/taskcluster/taskcluster/blob/main/dev-docs/best-practices/changelog.md), In this case, "A patch change is one that fixes a bug or makes a minor change which users can do their work without." -- users can do their work without this feature, just a bit more slowly.

2021-02-11 15:55 UTC, djmitche commented
Ah!  I didn't see the changes you pushed :(  There's a little circular-arrow button next to the reviews in the GitHub UI that will re-request a review, and hopefully get a response a little sooner.  Sorry!  I'll have a look shortly.

2021-02-11 19:07 UTC, djmitche requested changes
This looks great, but seems to have one lingering bug. When I click the delete icon, it displays a dialog that says "This will delete the `github/28673|djmitche/cli-ZN_L9m` client" (which is the clientId I was trying to delete).  When I click the "Delete Client" button, the dialog changes to

![image](https://user-images.githubusercontent.com/28673/107685625-379c6500-6c72-11eb-87ee-00ae7343e68c.png)

Any idea what's wrong?

2021-02-20 03:00 UTC, mrsVelena commented
I'm sorry for the late answer (I was on vacation and didn't have access to my computer). I actually cannot reach this step, because I don't have account with permissions to delete anything. But I assumed, there could be this problem, because I don't close Dialog onComplete after deleting. I tried to fix this, please check if this helped.

2021-02-22 14:49 UTC, djmitche commented
That fix seems perfect!  I noticed, though, that the client is still in the list after the deletion occurs.  Is that something you could fix?

Here's how to create clients:
 * On https://community-tc.services.mozilla.com/profile (after signing in) look for a scope like `auth:create-client:github/<something>`; mine is `auth:create-client:github/28673|djmitche/*`.  That gives you permission to create clients with that prefix (In my case, I can create clients like `github/28673|djmitche/foo` and `github/28673|djmitche/bar`).
 * Create a new client for yourself with a name you have permission for; mine might be `github/28673|djmitche/issue-2393`.  Give it scopes to create and delete clients -- for me that would be `auth:create-client:github/28673|djmitche/*` and auth:delete-client:github/28673|djmitche/*`.  Set the expiration to a few months from now.
 * On your development server, sign in with this new clientId and the accessToken it gave you (leave the certificate blank).  Now you can use your development server to create and delete clients all you want!

Sorry that's so complicated -- signing in is always difficult in development environments, it seems.

2021-03-01 23:19 UTC, mrsVelena commented
I fixed list update after client deletion. But I think the same bug would be on Roles page, too. What would be a better way to fix it? Through creating new PR?

2021-03-02 17:59 UTC, djmitche commented
Good thinking.  Yes, this PR has been around for a while and is (hopefully) ready to merge, so a new one is a good idea.

2021-03-02 18:04 UTC, djmitche approved these changes
And, indeed, this is great -- thanks for your patience and persistence!

2021-03-02 18:06 UTC, djmitche commented
(I merged main in here and fixed merge conflicts -- I'll merge back to main when the tests pass)

2021-03-02 18:32 UTC, merged