update instructions for generic-worker dev
taskcluster/taskcluster pull request #5775
Opened 2022-11-14 21:30 UTC by djmitche

This reflects what I had to do to get `./build.sh -t` passing.

It looks like some of these `go get` lines are in `build.sh`, but not the `go install` lines.  I recall that in a recent version (go1.18?) `go get` stopped installing binaries.  Maybe it makes sense to have `build.sh` run `go install` for _all_ of these, instead of this solution?

2022-11-15 15:16 UTC, matt-boris requested changes
Can confirm these steps work in getting `./build.sh -t` to run successfully.

Just requested changes for a couple stray ` + a missing changelog, thanks!

2022-11-15 15:16 UTC, matt-boris commented on workers/generic-worker/README.md
> +  go install github.com/taskcluster/livelog`
```suggestion
  go get github.com/taskcluster/livelog
  go install github.com/taskcluster/livelog
```

2022-11-15 15:51 UTC, petemoore requested changes
Thanks for updating the docs.

I think you can avoid needing the `go get` and the `go install` by installing a specific version, e.g.

```
go install github.com/taskcluster/taskcluster/v44/tools/taskcluster-proxy@v44.9.2
```

If we want this to stay up-to-date, we should probably punch in the version numbers at release time via regexp. What do you think?

2022-11-15 15:51 UTC, petemoore commented on workers/generic-worker/README.md
> +  go install github.com/taskcluster/taskcluster/v30/tools/taskcluster-proxy
v30?

2022-11-15 15:52 UTC, petemoore commented
> Maybe it makes sense to have `build.sh` run `go install` for _all_ of these, instead of this solution?

That's a fair point - I'm also happy for us to do it that way too, and the instructions be clear that you just run `build.sh`.

2022-11-15 17:01 UTC, djmitche commented on workers/generic-worker/README.md
> +  go install github.com/taskcluster/taskcluster/v30/tools/taskcluster-proxy
That was just from copy-paste :)

2022-11-15 18:40 UTC, djmitche commented
It appears that this fixes #5774!

2022-11-16 13:06 UTC, petemoore submitted a review, later dismissed

2022-11-16 13:07 UTC, petemoore commented
@djmitche Can you add a silent changelog?

2022-11-16 14:29 UTC, djmitche commented
> @djmitche Can you add a silent changelog?

Done

2022-11-18 09:21 UTC, lotas approved these changes

2022-11-18 14:35 UTC, petemoore approved these changes
Many thanks!

2022-11-21 10:58 UTC, lotas commented
Somehow I merged it locally after doing rebase, and it didn't automatically closed this PR, sorry.

Here's the merge commit https://github.com/taskcluster/taskcluster/commit/ed6c810036c94393ecd38e49e578d88042b23d09  (all commits preserved in history also)

2022-11-21 10:58 UTC, closed without merging