Replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
taskcluster/taskcluster pull request #6070
Opened 2023-02-16 13:22 UTC by Juneezee

The package `github.com/ghodss/yaml` is no longer actively maintained. See discussion in https://github.com/ghodss/yaml/issues/75 and https://github.com/ghodss/yaml/issues/80. [`sigs.k8s.io/yaml`](https://github.com/kubernetes-sigs/yaml) is a permanent fork of `github.com/ghodss/yaml`.

The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, but `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. Changes can be seen here [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), mostly bug fixes.

2023-02-16 16:20 UTC, petemoore commented
Thanks for this @Juneezee ! Indeed, it looks like the original repo is no longer actively maintained. I see there are a few different forks, but this seems like a reasonable choice.

2023-02-16 16:21 UTC, petemoore approved these changes
❤️

2023-02-20 13:29 UTC, matt-boris requested changes
Would you please change this to a patch level? I'll approve after this! Thanks for replacing!

2023-02-20 13:29 UTC, matt-boris commented on changelog/YHDKOgBXSZ-t6gQX9OvHbg.md
> +level: silent
```suggestion
level: patch
```

2023-02-20 13:53 UTC, matt-boris approved these changes

2023-02-20 14:14 UTC, merged