Include taskState in listLastFires
taskcluster/taskcluster pull request #6346
Opened 2023-06-27 17:24 UTC by lotas

Hook's fire status is somewhat confusing to users as it make it seem as hook last fires were successful, while in fact it only represents "task was scheduled". 
To make it easier to spot issues earlier, `hooks.listLastFires` includes `taskState` column, which represents tasks' last run state at the time of the call. 
New column is also added in UI to show both hook fire status and the task state

`taskState` represents tasks' last run state at the time of the call.

Github Bug/Issue: Fixes #6248

<img width="1971" alt="image" src="https://github.com/taskcluster/taskcluster/assets/83861/2b10fb7d-0198-4cd1-9e2a-24db2d31623f">

2023-06-27 17:26 UTC, lotas commented on services/hooks/src/api.js
> +      taskState: row.task_state || 'unscheduled',
this is missing tests still, will add soon

2023-06-28 12:59 UTC, matt-boris requested changes
Changes look great! Just requesting the new db method to have an updated description. 👍🏻

2023-06-28 13:04 UTC, lotas commented on db/versions/0088.yml
> +      Otherwise, page_size rows are returned at offset page_offset.
right! thanks

2023-06-28 13:44 UTC, matt-boris approved these changes
Awesome, thanks Yarik! 🚢

2023-06-28 13:48 UTC, merged